### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by adrian1234a** [djeman/android_vendor_sprd#1]
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp: In function 'android::status_t android::setDeviceStateIsConnection(audio_devices_t)':
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp:245:9: error: 'AUDIO_DEVICE_OUT_FM_HEADSET' was not declared in this scope
         AUDIO_DEVICE_OUT_FM_HEADSET,
         ^
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp:246:9: error: 'AUDIO_DEVICE_OUT_FM_SPEAKER' was not declared in this scope
         AUDIO_DEVICE_OUT_FM_SPEAKER,
         ^
In file included from vendor/sprd/modules/audio/normal/audio_hw.c:977:0:
vendor/sprd/modules/audio/normal/at_commands_generic.c: In function 'do_cmd_dual':
vendor/sprd/modules/audio/normal/at_commands_generic.c:29:5: warning: missing braces around initializer [-Wmissing-braces]
     T_AT_CMD process_at_cmd = {0};
     ^
vendor/sprd/modules/audio/normal/at_commands_generic.c:29:5: warning: (near initialization for 'process_at_cmd.at_cmd') [-Wmissing-braces]
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp: In function 'int android::sprd_fm_test_open()':
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp:558:43: error: 'AUDIO_DEVICE_OUT_FM_SPEAKER' was not declared in this scope
     AudioSystem::setDeviceConnectionState(AUDIO_DEVICE_OUT_FM_SPEAKER,
                                           ^
vendor/sprd/modules/audio/normal/at_commands_generic.c:29:5: warning: missing initializer for field 'at_cmd_priority' of 'T_AT_CMD' [-Wmissing-field-initializers]
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp:560:43: error: 'AUDIO_DEVICE_OUT_FM_HEADSET' was not declared in this scope
     AudioSystem::setDeviceConnectionState(AUDIO_DEVICE_OUT_FM_HEADSET,
                                           ^
vendor/sprd/modules/audio/normal/audio_hw.c:540:15: note: 'at_cmd_priority' declared here
    uint32_t   at_cmd_priority[MAX_AT_CMD_TYPE];
               ^
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp: In function 'int android::sprd_fm_test_play()':
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp:571:30: error: 'AUDIO_POLICY_FORCE_FOR_FM' was not declared in this scope
     AudioSystem::setForceUse(AUDIO_POLICY_FORCE_FOR_FM,AUDIO_POLICY_FORCE_NONE);
                              ^
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp:573:52: error: 'AUDIO_DEVICE_OUT_FM_HEADSET' was not declared in this scope
     status = AudioSystem::setDeviceConnectionState(AUDIO_DEVICE_OUT_FM_HEADSET,
                                                    ^
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp: In function 'int android::sprd_fm_test_stop()':
vendor/sprd/modules/audio/normal/audiotest/auto_audio_v2.cpp:588:43: error: 'AUDIO_DEVICE_OUT_FM_HEADSET' was not declared in this scope
     AudioSystem::setDeviceConnectionState(AUDIO_DEVICE_OUT_FM_HEADSET,
                                           ^
In file included from vendor/sprd/modules/audio/normal/audio_hw.c:977:0:

**Comment by djeman** [comment]
It's a test module not very important but this error is a problem to apply patches.
https://github.com/djeman/android_device_samsung_j3xnlte/blob/cm-13.0/patches/sprd-diff/frameworks_base.diff

**Comment by wbob** [comment]
for any reader hitting that: you'll see this when one of the patches in `patches/sprd-diff/` fails (see [/patches/sprd-diff/](https://github.com/djeman/android_device_samsung_sharkls-common/tree/cm-14.1/patches/sprd-diff). With the apply-script at `set -e` no further patches apply then, causing missing declarations.

Check why the patch fails to apply then
